# Configuration file for RAG Chatbot

# Embedding Model
embedding_model: "sentence-transformers/all-MiniLM-L6-v2"

# Vector Database
index_path: "models/vector_index.bin"
embedding_cache_path: "models/embeddings.pkl"
model_path: "models/"
# RAG Settings
retrieval:
  top_k: 5
  use_advanced: true  # Set to false for Basic RAG

# Guardrails
guardrails:
  confidence_threshold: 0.3
  blocked_keywords:
    - "hack"
    - "attack"
    - "malware"
    - "fraud"
    - "phishing"
    - "scam"
    - "exploit"

# UI Settings
ui:
  title: "📊 Financial RAG Chatbot"

data_path: "data/BPF1_17032024142500687.csv"
#slm_model: "TinyLlama/TinyLlama-1.1B-Chat-v1.0"
slm_model: "google/gemma-2b"

slm_models:
#  mistral: "mistralai/Mistral-7B-Instruct-v0.1"
#  gemma: "google/gemma-2b"
  tinyllama: "TinyLlama/TinyLlama-1.1B-Chat-v1.0"

default_model: "tinyllama"  # Set the default model
